Redis_host: redis.devopswithbnvst.uno
MongoDB_host: mongodb.devopswithbnvst.uno
Cart_host: cart.devopswithbnvst.uno
MySQL_host: mysql.devopswithbnvst.uno
RabbitMQ_host: rabbitmq.devopswithbnvst.uno
Catalogue_host: catalogue.devopswithbnvst.uno